# Application properties
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/group16
    username: root
    password: Makhumalo@2001
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080


debug: true

